---
title: "Some amazing data visualizations"
subtitle: "Seriously, can you believe how amazing?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(reactable)
library(harrypotter)
theme_set(theme_minimal(base_size = 25) +
            theme(plot.title.position = "plot",
                  legend.position = "bottom"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r, fig.width = 12, fig.cap = "Awesome caption"}
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(color = Species), size = 2) +
  geom_smooth(color = "magenta",
              fill = "cornflowerblue") +
  scale_colour_hp_d(option = "ravenclaw")
```


### Table

```{r tbl1}
reactable(iris)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Sepal Length by Species

```{r, iris-bar, fig.height = 10}
iris %>% 
  group_by(Species) %>% 
  summarize(mean_sepal_length = mean(Sepal.Length)) %>% 
  ungroup() %>% 
  mutate(Species = fct_reorder(Species, 
                               mean_sepal_length)) %>% 
  ggplot(aes(Species, mean_sepal_length)) +
  geom_col(fill = "cornflowerblue") +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "",
       y = "Mean Sepal Length")
```
